import {useState} from "react";

var postsNonCommentList =[
    {
      postId: "1",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      repliedTo: "",
      user_id: "user123",
      privacy: "public",
      created_at: "2023-12-24T08:00:00Z",
    },
    {
      postId: "2",
      body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      repliedTo: "",
      user_id: "user456",
      privacy: "private",
      created_at: "2023-12-23T10:30:00Z",
    },
    {
      postId: "3",
      body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      repliedTo: "",
      user_id: "user789",
      privacy: "public",
      created_at: "2023-12-22T15:45:00Z",
    },
    {
      postId: "4",
      body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      repliedTo: "",
      user_id: "user101",
      privacy: "private",
      created_at: "2023-12-21T12:20:00Z",
    },
    {
      postId: "5",
      body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      repliedTo: "",
      user_id: "user202",
      privacy: "public",
      created_at: "2023-12-20T17:00:00Z",
    },
    {
      postId: "10",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      repliedTo: "",
      user_id: "user123",
      privacy: "public",
      created_at: "2023-12-24T08:00:00Z",
    },
    {
      postId: "2",
      body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      repliedTo: "",
      user_id: "user456",
      privacy: "private",
      created_at: "2023-12-23T10:30:00Z",
    },
    {
      postId: "3",
      body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      repliedTo: "",
      user_id: "user789",
      privacy: "public",
      created_at: "2023-12-22T15:45:00Z",
    },
    {
      postId: "4",
      body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      repliedTo: "",
      user_id: "user101",
      privacy: "private",
      created_at: "2023-12-21T12:20:00Z",
    },
    {
      postId: "5",
      body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      repliedTo: "",
      user_id: "user202",
      privacy: "public",
      created_at: "2023-12-20T17:00:00Z",
    },
    {
      postId: "100",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      repliedTo: "",
      user_id: "user123",
      privacy: "public",
      created_at: "2023-12-24T08:00:00Z",
    },
    {
      postId: "2",
      body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      repliedTo: "",
      user_id: "user456",
      privacy: "private",
      created_at: "2023-12-23T10:30:00Z",
    },
    {
      postId: "3",
      body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      repliedTo: "",
      user_id: "user789",
      privacy: "public",
      created_at: "2023-12-22T15:45:00Z",
    },
    {
      postId: "4",
      body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      repliedTo: "",
      user_id: "user101",
      privacy: "private",
      created_at: "2023-12-21T12:20:00Z",
    },
    {
      postId: "5",
      body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      repliedTo: "",
      user_id: "user202",
      privacy: "public",
      created_at: "2023-12-20T17:00:00Z",
    },
  ];

  const skills = [
    "ReactDeveloper",
    "Singer",
    "Entertainer",
    "Pilot",
    "Engineering",
  ];

  const blocked = [
    {name:'Samantha Rodriguez'},
    {name:'Marcus Thompson'},
    {name:'Olivia Patel'},
    {name:'Elijah Nguyen'},
    {name:'Isabella Chang'},
    {name:'Caleb Mitchell'},
    {name:'Sophia Khan'},
    {name:'Aiden Sullivan'},
    {name:'Ava Gupta'},
    {name:'Jackson Kim'},
  ];
  
  const followers = [
    {name:'Emily Johnson'},
    {name:'Noah Williams'},
    {name:'Mia Brown'},
    {name:'Liam Jones'},
    {name:'Emma Garcia'},
    {name:'Jacob Martinez'},
    {name:'Avery Wilson'},
    {name:'William Anderson'},
    {name:'Sophia Lopez'},
    {name:'Alexander Lee'},
  ];
  
  const following = [
    {name:'Madison Moore'},
    {name:'Ethan Davis'},
    {name:'Chloe Jackson'},
    {name:'Mason White'},
    {name:'Grace Harris'},
    {name:'Logan Taylor'},
    {name:'Ella Thomas'},
    {name:'James Clark'},
    {name:'Aria Robinson'},
    {name:'Daniel Lewis'},
  ];

  var postsCommentList = [
    {
      postId: "6",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      repliedTo: "1",
      user_id: "user123",
      privacy: "public",
      created_at: "2023-12-24T08:00:00Z",
    },
    {
      postId: "7",
      body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      repliedTo: "1",
      user_id: "user456",
      privacy: "private",
      created_at: "2023-12-23T10:30:00Z",
    },
    {
      postId: "8",
      body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      repliedTo: "1",
      user_id: "user789",
      privacy: "public",
      created_at: "2023-12-22T15:45:00Z",
    },
    {
      postId: "9",
      body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      repliedTo: "1",
      user_id: "user101",
      privacy: "private",
      created_at: "2023-12-21T12:20:00Z",
    },
    {
      postId: "10",
      body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      repliedTo: "1",
      user_id: "user202",
      privacy: "public",
      created_at: "2023-12-20T17:00:00Z",
    },
    {
      postId: "6",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      repliedTo: "1",
      user_id: "user123",
      privacy: "public",
      created_at: "2023-12-24T08:00:00Z",
    },
    {
      postId: "7",
      body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      repliedTo: "1",
      user_id: "user456",
      privacy: "private",
      created_at: "2023-12-23T10:30:00Z",
    },
    {
      postId: "8",
      body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      repliedTo: "1",
      user_id: "user789",
      privacy: "public",
      created_at: "2023-12-22T15:45:00Z",
    },
    {
      postId: "9",
      body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      repliedTo: "1",
      user_id: "user101",
      privacy: "private",
      created_at: "2023-12-21T12:20:00Z",
    },
    {
      postId: "10",
      body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      repliedTo: "1",
      user_id: "user202",
      privacy: "public",
      created_at: "2023-12-20T17:00:00Z",
    },
    {
      postId: "6",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      repliedTo: "1",
      user_id: "user123",
      privacy: "public",
      created_at: "2023-12-24T08:00:00Z",
    },
    {
      postId: "7",
      body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      repliedTo: "1",
      user_id: "user456",
      privacy: "private",
      created_at: "2023-12-23T10:30:00Z",
    },
    {
      postId: "8",
      body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      repliedTo: "1",
      user_id: "user789",
      privacy: "public",
      created_at: "2023-12-22T15:45:00Z",
    },
    {
      postId: "9",
      body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      repliedTo: "1",
      user_id: "user101",
      privacy: "private",
      created_at: "2023-12-21T12:20:00Z",
    },
    {
      postId: "10",
      body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      repliedTo: "1",
      user_id: "user202",
      privacy: "public",
      created_at: "2023-12-20T17:00:00Z",
    },
  ];